name: Multi-branch

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  multi-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run the scripts
        run: |
          sleep 30
          echo "multi-branch job done"
