name: Multi-branch

on:
  pull_request:
  push:

jobs:
  multi-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run the scripts
        run: |
          sleep 1200
          echo "multi-branch job done"
