name: Multi-branch

on:
  pull_request:
  push:

jobs:
  multi-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./multi-branch.js')
            await script({github, context, core})
