name: Multi-branch

on:
  push:

jobs:
  multi-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./.github/workflows/multi-branch.js')
            await script({github, context, core})
