name: Remove Label on New Commit

on:
  pull_request:
    types:
      - synchronize

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - name: Remove specific label
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo, number: issue_number } = context.issue;
          const labelToRemove = "your-label-name";  // Replace 'your-label-name' with the name of the label you want to remove

          // Fetch current labels on the PR
          const { data: currentLabels } = await github.issues.listLabelsOnIssue({ owner, repo, issue_number });

          // Check if the label is present
          const hasLabel = currentLabels.some(label => label.name === labelToRemove);

          if (hasLabel) {
            await github.issues.removeLabel({ owner, repo, issue_number, name: labelToRemove });
            console.log(`Removed label "${labelToRemove}" from PR #${issue_number}`);
          } else {
            console.log(`Label "${labelToRemove}" not found on PR #${issue_number}`);
          }
